super_franqueador_mapa:
    path:     /mapa.html
    defaults: { _controller: SuperFranqueadorBundle:Default:mapa }

super_franqueador_localidade:
    path:     /localidade
    defaults: { _controller: SuperFranqueadorBundle:Default:localidade }

super_franqueador_dashboard:
    path:     /dashboard.html
    defaults: { _controller: SuperFranqueadorBundle:Default:dashboard }

super_franqueador_enquete:
    resource: "@SuperEnqueteBundle/Resources/config/routing.yml"
    prefix:   /enquete

super_franqueador_feedback:
    resource: "@SuperFeedbackBundle/Resources/config/routing.yml"
    prefix:   /feedback

super_franqueador_pesquisa:
    path:     /pesquisa.html
    defaults: { _controller: SuperBaseBundle:Default:pesquisa }

super_franqueador_comentario_cliente:
    path:     /comentario/index.html
    defaults: { _controller: SuperFranqueadorBundle:Comentario:index }

super_franqueador_comentario_cliente_view:
    path:     /comentario/view/{idFranqueador}/{idUsuario}
    defaults: { _controller: SuperFranqueadorBundle:Comentario:viewComentario }
    requirements:
            idFranqueador: \d+
            idUsuario: \d+

super_franqueador_transacao:
    path:     /transacoes
    defaults: { _controller: SuperFranqueadorBundle:Transacao:index }

super_promocao:
    resource: "@SuperPromocaoBundle/Resources/config/routing.yml"
    prefix:   /promocao

super_cardapio:
    resource: "@SuperCardapioBundle/Resources/config/routing.yml"
    prefix:   /cardapio

super_franqueador_usuario:
    path:     /usuario/index.html
    defaults: { _controller: SuperFranqueadorBundle:Usuario:index }

super_franqueador_usuario_status:
    path:     /usuario/status
    defaults: { _controller: SuperFranqueadorBundle:Usuario:status }

super_franqueador_usuario_view:
    path:     /usuario/view/{idFranqueador}/{idUsuario}
    defaults: { _controller: SuperFranqueadorBundle:Usuario:view }
    requirements:
            idFranqueador: \d+
            idUsuario: \d+

########## FRANQUIA ###############
super_franquia_index:
    path:     /franquia/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:index, idFranqueador: 0 }
    requirements:
        idFranqueador: \d+

super_franquia_edit:
    path:     /franquia/editar/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }
    requirements:
        id: \d+