super_franqueador:
    path:     /
    defaults: { _controller: SuperBaseBundle:Default:index }

super_franqueador_index:
    path:     /index.html
    defaults: { _controller: SuperFranqueadorBundle:Default:index }

super_franqueador_create:
    path:     /cadastro.html
    defaults: { _controller: SuperFranqueadorBundle:Default:create }

super_franqueador_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperFranqueadorBundle:Default:edit }
    requirements:
        id: \d+

super_franqueador_localidade:
    path:     /localidade
    defaults: { _controller: SuperFranquiaBundle:Default:localidade }

super_franqueador_mapa:
    path:     /mapa.html
    defaults: { _controller: SuperFranqueadorBundle:Default:mapa }

super_dashboard:
    path:     /dashboard
    defaults: { _controller: SuperFranqueadorBundle:Default:franquiadorDashboard }