super_franqueador_mapa:
    path:     /mapa.html
    defaults: { _controller: SuperFranqueadorBundle:Default:mapa }

super_franqueador_dashboard:
    path:     /dashboard.html
    defaults: { _controller: SuperFranqueadorBundle:Default:dashboard }

super_franqueador_enquete:
    resource: "@SuperEnqueteBundle/Resources/config/routing.yml"
    prefix:   /enquete

super_franqueador_feedback:
    resource: "@SuperFeedbackBundle/Resources/config/routing.yml"
    prefix:   /feedback

super_franqueador_pesquisa:
    path:     /pesquisa.html
    defaults: { _controller: SuperBaseBundle:Default:pesquisa }


########## FRANQUIA ###############
super_franquia_index:
    path:     /{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:index }
    requirements:
        idFranqueador: \d+

super_franquia_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }
    requirements:
        id: \d+