super_franqueador_template:
    path:     /franqueador/template-email/index.html
    defaults: { _controller: SuperTemplateBundle:Franqueador:index }

super_franqueador_template_create:
    path:     /franqueador/template-email/cadastro.html
    defaults: { _controller: SuperTemplateBundle:Franqueador:create }
