######### USUARIO #########
super_mobile_usuario_autenticar:
    path:     /usuario/autenticar
    defaults: { _controller: SuperMobileBundle:Usuario:autenticar }
    methods:  [POST]

super_mobile_usuario_logout:
    path:     /usuario/logout
    defaults: { _controller: SuperMobileBundle:Usuario:logout }
    methods:  [POST]

super_mobile_usuario_cadastrar:
    path:     /usuario/cadastrar
    defaults: { _controller: SuperMobileBundle:Usuario:cadastrar }
    methods:  [POST]

super_mobile_usuario_recuperar_senha:
    path:     /usuario/recuperar-senha
    defaults: { _controller: SuperMobileBundle:Usuario:recuperarSenha }
    methods:  [POST]


######### ENQUETE #########
super_mobile_enquete_responder:
    path:     /enquete/responder
    defaults: { _controller: SuperMobileBundle:Enquete:responder }
    methods:  [POST]


######### BONUS #########
super_mobile_bonus_listar:
    path:     /bonus/listar
    defaults: { _controller: SuperMobileBundle:Bonus:listar }
    methods:  [POST]


######### FRANQUEADOR #########
super_mobile_franqueador_listar_lojas:
    path:     /franqueador/listar/lojas
    defaults: { _controller: SuperMobileBundle:Franqueador:listarLojas }
    methods:  [POST]


######### FRANQUIA #########
super_mobile_franquia_opinar:
    path:     /franquia/opinar
    defaults: { _controller: SuperMobileBundle:Franquia:opinar }
    methods:  [POST]

super_mobile_franquia_listar_promocao:
    path:     /franquia/listar/promocao
    defaults: { _controller: SuperMobileBundle:Franquia:listarPromocao }
    methods:  [POST]

super_mobile_franquia_listar_cardapio:
    path:     /franquia/listar/cardapio
    defaults: { _controller: SuperMobileBundle:Franquia:listarCardapio }
    methods:  [POST]