manter_promocao_index:
    path:     /manter-promocao
    defaults: { _controller: SuperPromocaoBundle:Promocao:index }

manter_promocao_create:
    path:     /manter-promocao/create
    defaults: { _controller: SuperPromocaoBundle:Promocao:create }

manter_promocao_edit:
    path:     /manter-promocao/edit/{id}
    defaults: { _controller: SuperPromocaoBundle:Promocao:edit }

manter_promocao_delete:
    path:     /manter-promocao/delete/{id}
    defaults: { _controller: SuperPromocaoBundle:Promocao:delete }
