manter_promocao_index:
    path:     /index.html
    defaults: { _controller: SuperPromocaoBundle:Promocao:index }

manter_promocao_create:
    path:     /cadastro.html
    defaults: { _controller: SuperPromocaoBundle:Promocao:create }

manter_promocao_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperPromocaoBundle:Promocao:edit }

manter_promocao_delete:
    path:     /delete/{id}
    defaults: { _controller: SuperPromocaoBundle:Promocao:delete }
