super_feedback_index:
    path:     /
    defaults: { _controller: SuperFeedbackBundle:Feedback:index }

super_feedback_create:
    path:     /create
    defaults: { _controller: SuperFeedbackBundle:Feedback:create }

super_feedback_edit:
    path:     /edit/{id}
    defaults: { _controller: SuperFeedbackBundle:Feedback:edit }

super_feedback_delete:
    path:     /delete/{id}
    defaults: { _controller: SuperFeedbackBundle:Feedback:delete }

super_feedback_email:
    path:     /email
    defaults: { _controller: SuperFeedbackBundle:Feedback:email }

super_feedback_set_email:
    path:     /email/set
    defaults: { _controller: SuperFeedbackBundle:Feedback:setEmailFeedBack }
