super_franqueador_feedback_index:
    path:     /index.html
    defaults: { _controller: SuperFeedbackBundle:Feedback:index }

super_franqueador_feedback_create:
    path:     /cadastro.html
    defaults: { _controller: SuperFeedbackBundle:Feedback:create }

super_franqueador_feedback_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperFeedbackBundle:Feedback:edit }

super_franqueador_feedback_delete:
    path:     /delete/{id}
    defaults: { _controller: SuperFeedbackBundle:Feedback:delete }

super_franqueador_feedback_relatorio:
    path:     /relatorio/{id}
    defaults: { _controller: SuperFeedbackBundle:Feedback:relatorio }

super_franqueador_feedback_email:
    path:     /email
    defaults: { _controller: SuperFeedbackBundle:Feedback:email }

super_franqueador_feedback_set_email:
    path:     /email/set
    defaults: { _controller: SuperFeedbackBundle:Feedback:setEmailFeedBack }