services:
    service.feedback:
              class: Super\FeedbackBundle\Service\FeedBack
              arguments:  ["@service_container"]

    service.feedback_email:
              class: Super\FeedbackBundle\Service\EmailFeedBack
              arguments:  ["@service_container"]