services:
    service.feedback:
        class: Super\FeedbackBundle\Service\FeedBack
        arguments:  ["@service_container"]
    service.feedback_email:
        class: Super\FeedbackBundle\Service\EmailFeedBack
        arguments:  ["@service_container"]
    service.feedback_questao:
        class: Super\FeedbackBundle\Service\FeedbackQuestao
        arguments:  ["@service_container"]
    service.feedback_questao_resposta:
        class: Super\FeedbackBundle\Service\FeedbackQuestaoResposta
        arguments:  ["@service_container"]
    service.tipo_feedback:
        class: Super\FeedbackBundle\Service\TipoFeedback
        arguments:  ["@service_container"]