######## ADMINSITRADOR #########
super_base:
    resource: "@SuperBaseBundle/Resources/config/routing.yml"
    prefix:   /administrador


######## FRANQUEADOR #########
franqueador:
    resource: "@SuperFranqueadorBundle/Resources/config/routing.yml"
    prefix:   /franqueador


######## FRANQUIA #########
super_usuario:
    resource: "@SuperFranquiaBundle/Resources/config/routing.yml"
    prefix:   /franquia


######## MOBILE #########
super_mobile:
    resource: "@SuperMobileBundle/Resources/config/routing.yml"
    prefix:   /mobile


######## TRANSACAO #########
super_transacao:
    resource: "@SuperTransacaoBundle/Resources/config/routing.yml"
    prefix:   /transacao


######## FRNETE CAIXA OPERADOR #########
super_operador_home:
    path:     /utilizar-creditos
    defaults: { _controller: SuperOperadorBundle:Default:utilizarCredito }

######## FRNETE CAIXA OPERADOR #########
super_template:
    resource: "@SuperTemplateBundle/Resources/config/routing.yml"
    prefix:   /


######## SECURITY #########
super_security:
    resource: "@SuperSecurityBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBaseBundle/Resources/config/routing.yml"

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
