super_mobile:
    resource: "@SuperMobileBundle/Resources/config/routing.yml"
    prefix:   /service/mobile

site:
    resource: "@SiteBundle/Resources/config/routing.yml"

super_base:
    resource: "@SuperBaseBundle/Resources/config/routing.yml"
    prefix:   /super

super_security:
    resource: "@SuperSecurityBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBaseBundle/Resources/config/routing.yml"
