site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /site

super_base:
    resource: "@SuperBaseBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBaseBundle/Resources/config/routing.yml"
    prefix:   /
