site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

site_login:
    pattern: /entrar.html
    defaults: { _controller: SiteBundle:Usuario:login }

site_esqueci_senha:
    path:     /esqueci-minha-senha.html
    defaults: { _controller: SiteBundle:Usuario:login }

site_ativar_cadastro:
    path:     /ativar-cadastro/{token}
    defaults: { _controller: SiteBundle:Usuario:ativarCadastro }

site_fale_conosco:
    path:     /fale-conosco.html
    defaults: { _controller: SiteBundle:Site:faleConosco }