### SUPER ###

super_home:
    path:     /
    defaults: { _controller: SuperBaseBundle:Default:index }

super_promocao:
    resource: "@SuperPromocaoBundle/Resources/config/routing.yml"
    prefix:   /promocao

super_cardapio:
    resource: "@SuperCardapioBundle/Resources/config/routing.yml"
    prefix:   /cardapio

super_franquia:
    resource: "@SuperFranquiaBundle/Resources/config/routing.yml"
    prefix:   /franqueador/franquia


### FRANQUEADOR ###

super_franqueador:
    resource: "@SuperFranqueadorBundle/Resources/config/routing.yml"
    prefix:   /franqueador

super_feedback:
    resource: "@SuperFeedbackBundle/Resources/config/routing.yml"
    prefix:   /franqueador/feedback

super_pesquisa:
    path:     /franqueador/pesquisa.html
    defaults: { _controller: SuperBaseBundle:Default:pesquisa }

super_enquete:
    resource: "@SuperEnqueteBundle/Resources/config/routing.yml"
    prefix:   /franqueador/enquete

super_operador:
    resource: "@SuperOperadorBundle/Resources/config/routing.yml"
    prefix:   /franqueador/operador

super_usuario:
    resource: "@SuperUsuarioBundle/Resources/config/routing.yml"
    prefix:   /franqueador/usuario

super_franqueador_franquia:
    resource: "@SuperFranquiaBundle/Resources/config/franqueador_routing.yml"
    prefix:   /franqueador/franquia