### SUPER ###
super_home:
    path:     /
    defaults: { _controller: SuperBaseBundle:Default:index }

super_ftp_index:
    path:     /configuracao-ftp/index.html
    defaults: { _controller: SuperBaseBundle:ConfiguracaoFtp:index }

super_ftp_create:
    path:     /configuracao-ftp/{id}
    defaults: { _controller: SuperBaseBundle:ConfiguracaoFtp:create }
    requirements:
            id: \d+

######## FRANQUEADOR #########
super_franqueador_index:
    path:     /franqueador/index.html
    defaults: { _controller: SuperFranqueadorBundle:Default:index }

super_franqueador_create:
    path:     /franqueador/cadastro.html
    defaults: { _controller: SuperFranqueadorBundle:Default:create }

super_franqueador_edit:
    path:     /franqueador/editar/{id}
    defaults: { _controller: SuperFranqueadorBundle:Default:edit }
    requirements:
        id: \d+


######## FRANQUIA #########
super_franquia_index_super:
    path:     /franquia/index.html
    defaults: { _controller: SuperFranquiaBundle:Default:superIndex }
    requirements:
        idFranqueador: \d+

super_franquia_create:
    path:     /franquia/cadastrar/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:create }
    requirements:
        idFranqueador: \d+

super_franquia_edit_super:
    path:     /franquia/editar/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }
    requirements:
        id: \d+

super_franquia_index_franquia_super:
    path:     /franquia/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:index }
    requirements:
        idFranqueador: \d+


################## faq
super_faq_index:
    path:     /faq/index.html
    defaults: { _controller: SuperBaseBundle:Faq:index }

super_faq_create:
    path:     /faq/cadastro.html
    defaults: { _controller: SuperBaseBundle:Faq:create }

super_faq_edit:
    path:     /faq/editar
    defaults: { _controller: SuperBaseBundle:Faq:edit }

super_faq_delete:
    path:     /faq/delete/{id}
    defaults: { _controller: SuperBaseBundle:Faq:delete }