super_home:
    path:     /
    defaults: { _controller: SuperBaseBundle:Default:index }

super_enquete:
    resource: "@SuperEnqueteBundle/Resources/config/routing.yml"
    prefix:   /enquete

super_promocao:
    resource: "@SuperPromocaoBundle/Resources/config/routing.yml"
    prefix:   /promocao

super_cardapio:
    resource: "@SuperCardapioBundle/Resources/config/routing.yml"
    prefix:   /cardapio

super_franqueador:
    resource: "@SuperFranqueadorBundle/Resources/config/routing.yml"
    prefix:   /franqueador

super_operador:
    resource: "@SuperOperadorBundle/Resources/config/routing.yml"
    prefix:   /operador

super_usuario:
    resource: "@SuperUsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

super_franquia:
    resource: "@SuperFranquiaBundle/Resources/config/routing.yml"
    prefix:   /franquia

super_pesquisa:
    path:     /pesquisa.html
    defaults: { _controller: SuperBaseBundle:Default:pesquisa }

