### SUPER ###
super_home:
    path:     /
    defaults: { _controller: SuperBaseBundle:Default:index }

super_promocao:
    resource: "@SuperPromocaoBundle/Resources/config/routing.yml"
    prefix:   /promocao

super_cardapio:
    resource: "@SuperCardapioBundle/Resources/config/routing.yml"
    prefix:   /cardapio


######## FRANQUEADOR #########
super_franqueador_index:
    path:     /franqueador/index.html
    defaults: { _controller: SuperFranqueadorBundle:Default:index }

super_franqueador_create:
    path:     /franqueador/cadastro.html
    defaults: { _controller: SuperFranqueadorBundle:Default:create }

super_franqueador_edit:
    path:     /franqueador/editar/{id}
    defaults: { _controller: SuperFranqueadorBundle:Default:edit }
    requirements:
        id: \d+


######## FRANQUIA #########
super_franquia_index_super:
    path:     /franquia/index.html
    defaults: { _controller: SuperFranquiaBundle:Default:superIndex }
    requirements:
        idFranqueador: \d+

super_franquia_create:
    path:     /franquia/cadastrar/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:create }
    requirements:
        idFranqueador: \d+