manter_homepage:
    path:     /hello/{name}
    defaults: { _controller: ManterBundle:Default:index }

manter_promocao_index:
    path:     /manter-promocao
    defaults: { _controller: SuperManterBundle:Promocao:index }

manter_promocao_create:
    path:     /manter-promocao/create
    defaults: { _controller: SuperManterBundle:Promocao:create }

manter_promocao_edit:
    path:     /manter-promocao/edit/{id}
    defaults: { _controller: SuperManterBundle:Promocao:edit }

manter_promocao_delete:
    path:     /manter-promocao/delete/{id}
    defaults: { _controller: SuperManterBundle:Promocao:delete }

manter_enquete_index:
    path:     /manter-enquete
    defaults: { _controller: SuperManterBundle:Enquete:index }

manter_enquete_create:
    path:     /manter-enquete/create
    defaults: { _controller: SuperManterBundle:Enquete:create }

manter_enquete_edit:
    path:     /manter-enquete/edit/{id}
    defaults: { _controller: SuperManterBundle:Enquete:edit }

manter_enquete_delete:
    path:     /manter-enquete/delete/{id}
    defaults: { _controller: SuperManterBundle:Enquete:delete }