services:
    service.promocao:
          class: Super\ManterBundle\Service\Promocao
          arguments:  ["@service_container"]

    service.enquete:
              class: Super\ManterBundle\Service\Enquete
              arguments:  ["@service_container"]

    service.resposta:
              class: Super\ManterBundle\Service\Resposta
              arguments:  ["@service_container"]