manter_enquete_index:
    path:     /manter-enquete
    defaults: { _controller: SuperEnqueteBundle:Enquete:index }

manter_enquete_create:
    path:     /manter-enquete/create
    defaults: { _controller: SuperEnqueteBundle:Enquete:create }

manter_enquete_edit:
    path:     /manter-enquete/edit/{id}
    defaults: { _controller: SuperEnqueteBundle:Enquete:edit }

manter_enquete_delete:
    path:     /manter-enquete/delete/{id}
    defaults: { _controller: SuperEnqueteBundle:Enquete:delete }

manter_cardapio_index:
    path:     /manter-cardapio
    defaults: { _controller: SuperCardapioBundle:Cardapio:index }

manter_cardapio_create:
    path:     /manter-cardapio/create
    defaults: { _controller: SuperCardapioBundle:Cardapio:create }

manter_cardapio_edit:
    path:     /manter-cardapio/edit/{id}
    defaults: { _controller: SuperCardapioBundle:Cardapio:edit }

manter_cardapio_delete:
    path:     /manter-cardapio/delete/{id}
    defaults: { _controller: SuperCardapioBundle:Cardapio:delete }
