manter_enquete_index:
    path:     /
    defaults: { _controller: SuperEnqueteBundle:Enquete:index }

manter_enquete_create:
    path:     /cadastrar
    defaults: { _controller: SuperEnqueteBundle:Enquete:create }

manter_enquete_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperEnqueteBundle:Enquete:edit }

manter_enquete_delete:
    path:     /excluir/{id}
    defaults: { _controller: SuperEnqueteBundle:Enquete:delete }