Base\BaseBubdle\Entity\TbEnquete:
    properties:
        noEnquete:
            - NotBlank: ~
        nuPontos:
            - NotBlank: ~
        nuBonus:
            - NotBlank: ~
        dtFim:
            - NotBlank: ~