super_operador_index:
    path:     /index.html
    defaults: { _controller: SuperOperadorBundle:Default:index }

super_operador_create:
    path:     /cadastro.html
    defaults: { _controller: SuperOperadorBundle:Default:create }

super_operador_edit:
    path:     /editar
    defaults: { _controller: SuperOperadorBundle:Default:edit }