manter_cardapio_index:
    path:     /index.html
    defaults: { _controller: SuperCardapioBundle:Cardapio:index }

manter_cardapio_create:
    path:     /cadastro.html
    defaults: { _controller: SuperCardapioBundle:Cardapio:create }

manter_cardapio_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperCardapioBundle:Cardapio:edit }

manter_cardapio_delete:
    path:     /delete/{id}
    defaults: { _controller: SuperCardapioBundle:Cardapio:delete }

manter_cardapio_view:
    path:     /visualizar/{id}
    defaults: { _controller: SuperCardapioBundle:Cardapio:ver }