super_franquia_dashboard:
    path:     /dashboard.html
    defaults: { _controller: SuperFranquiaBundle:Default:index }

super_franquia_buscar_usuario:
    path:     /usuario/buscar
    defaults: { _controller: SuperFranquiaBundle:Default:buscarUsuario }

super_franquia_transacao:
    path:     /transacoes
    defaults: { _controller: SuperFranquiaBundle:Default:transacao }

super_franquia_operador:
    resource: "@SuperOperadorBundle/Resources/config/routing.yml"
    prefix:   /operador

super_usuario:
    resource: "@SuperUsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario