super_franquia_index:
    path:     /
    defaults: { _controller: SuperFranquiaBundle:Default:index }

super_franquia_create:
    path:     /create
    defaults: { _controller: SuperFranquiaBundle:Default:create }

super_franquia_edit:
    path:     /edit/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }
