super_franquia_index:
    path:     /
    defaults: { _controller: SuperFranquiaBundle:Default:index }

super_franquia_create:
    path:     /cadastrar/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:create }

super_franquia_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }

super_franquia_buscar_usuario:
    path:     /usuario/buscar
    defaults: { _controller: SuperFranquiaBundle:Default:buscarUsuario }