super_franquia_index:
    path:     /{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:index }
    requirements:
        idFranqueador: \d+

super_franquia_create:
    path:     /cadastrar/{idFranqueador}
    defaults: { _controller: SuperFranquiaBundle:Default:create }
    requirements:
        idFranqueador: \d+

super_franquia_edit:
    path:     /editar/{id}
    defaults: { _controller: SuperFranquiaBundle:Default:edit }
    requirements:
        id: \d+

super_franquia_buscar_usuario:
    path:     /usuario/buscar
    defaults: { _controller: SuperFranquiaBundle:Default:buscarUsuario }

