super_transacao_processar_arquivo_retorno:
    path:     /processar-arquivo-retorno
    defaults: { _controller: SuperTransacaoBundle:Default:processarArquivoRetorno }

super_transacao_saque:
    path:     /saque
    defaults: { _controller: SuperTransacaoBundle:Default:saque }

super_requisicao_transacao_usuario:
    path:     /requisicao-transacao-usuario
    defaults: { _controller: SuperTransacaoBundle:Default:requisicaoTransacaoUsuario }
